-- Era assignment fixes generated by audit_eras_v2.py
-- 87 changes

BEGIN;

UPDATE collected_editions SET era_id = 'ef8c9832-e06d-4028-ae89-a2bb5eb13e1c' WHERE id = '00a03dc6-4bdb-4eb4-9d01-9ab42fbcd95b'; -- Star-Lord by Chip Zdarsky: all-new-all-different -> dawn-of-krakoa
UPDATE collected_editions SET era_id = '93f0e7e8-0cc2-4f06-9090-6ad14520bece' WHERE id = '093e3e9f-530a-46b1-b0b1-66f684b2939a'; -- X-Men: Messiah War: bendis-avengers -> event-age
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = '0e1729be-b95c-4a53-a110-12b871ba37cc'; -- Ultimate Fantastic Four Omnibus Vol. 2: marvel-knights-ultimate -> bronze-age
UPDATE collected_editions SET era_id = '49fd3e6f-0cd3-48f5-abbe-7c90e59acfa6' WHERE id = '0f5377ee-5991-4b12-a844-d72874a9d18f'; -- Deathlok: The Complete Collection (Original): bronze-age -> rise-of-x-men
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '106338ce-a3bf-4a51-aecb-e1ff0a9d68e9'; -- Marvel Premier Collection: Planet Hulk: bendis-avengers -> birth-of-marvel
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '10b94252-ba6a-4c14-9a9c-485dc7d7d365'; -- Ultimate Fantastic Four Epic Collection: The Fantastic: marvel-knights-ultimate -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '10d0a9bc-cdab-4c6d-9e88-9c2a4720c733'; -- The Ultimates Epic Collection: Super-Human: marvel-knights-ultimate -> the-expansion
UPDATE collected_editions SET era_id = 'dfdb0620-290e-42c7-876a-cf3fec5001b3' WHERE id = '12e03474-2248-443d-abdb-241f02be8c6c'; -- Avengers: Under Siege: event-age -> bendis-avengers
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '177ddfdc-7f84-4441-897d-496535c9a954'; -- Hawkeye Epic Collection: The Avenging Archer: rise-of-x-men -> the-expansion
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = '1ddc92d6-1ba9-4a1b-a558-80a54028d768'; -- Iron Man Omnibus Vol. 2: birth-of-marvel -> bronze-age
UPDATE collected_editions SET era_id = '93f854fe-cd0a-4070-9a30-1f671374200e' WHERE id = '21d869b7-82ae-4fcf-aba9-7f1854d4c92e'; -- Iron Man (2025) Vol. 1: current-ongoings -> blood-hunt-doom
UPDATE collected_editions SET era_id = 'ef8c9832-e06d-4028-ae89-a2bb5eb13e1c' WHERE id = '27ecd2bc-9f58-487d-bf21-2578723ff7f7'; -- New Mutants by Zeb Wells: Complete Collection: bendis-avengers -> dawn-of-krakoa
UPDATE collected_editions SET era_id = '93f0e7e8-0cc2-4f06-9090-6ad14520bece' WHERE id = '2f9a597f-923b-4d03-9a8d-d2376c0e7bdd'; -- Fantastic Four Epic Collection: Atlantis Rising: speculation-crash -> event-age
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '314b4a75-0d5b-4759-8331-71f129211643'; -- Ultimate Spider-Man Epic Collection: Learning Curve: marvel-knights-ultimate -> the-expansion
UPDATE collected_editions SET era_id = 'e8879226-9a97-4fdb-a2d8-484a3579385d' WHERE id = '3862a96d-6b6b-47f5-a894-905a77ea4d7d'; -- Captain America Epic Collection: The Secret Empire: bronze-age -> all-new-all-different
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '38fe298b-267f-4da8-affe-8f6d751473d3'; -- Warlock by Jim Starlin (Complete Collection): bronze-age -> birth-of-marvel
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '3950adb4-3684-433b-9451-5165bbded1e1'; -- Marvel vs DC / DC vs Marvel: speculation-crash -> the-expansion
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '3aa274f0-b3bd-4579-8b08-6abcf9b325c3'; -- Fantastic Four by Jonathan Hickman Omnibus Vol. 1: hickman-saga -> birth-of-marvel
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '3b1e2200-5d50-4f01-b3b0-6f201666aefb'; -- Sensational She-Hulk by John Byrne Omnibus: event-age -> birth-of-marvel
UPDATE collected_editions SET era_id = '93f0e7e8-0cc2-4f06-9090-6ad14520bece' WHERE id = '42b0772d-e063-482d-b285-5d5f0240e544'; -- Deadpool Epic Collection: The Circle Chase: speculation-crash -> event-age
UPDATE collected_editions SET era_id = '49fd3e6f-0cd3-48f5-abbe-7c90e59acfa6' WHERE id = '4507efec-e9ef-4fee-8a85-a340c9e935af'; -- Incredible Hulk Omnibus Vol. 5 (Mantlo/Buscema): bronze-age -> rise-of-x-men
UPDATE collected_editions SET era_id = '49fd3e6f-0cd3-48f5-abbe-7c90e59acfa6' WHERE id = '45571a22-2aef-41ee-89cd-7ac73105e955'; -- X-Men: The Messiah Trilogy Omnibus: bendis-avengers -> rise-of-x-men
UPDATE collected_editions SET era_id = '93f0e7e8-0cc2-4f06-9090-6ad14520bece' WHERE id = '46dac3ec-cd07-491e-b3dc-f8c97268e6a1'; -- Fantastic Four Epic Collection: This Flame This Fury: speculation-crash -> event-age
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '49cf7c17-12bf-4ade-bd2b-8e168c66a953'; -- All-New All-Different Avengers by Mark Waid: all-new-all-different -> birth-of-marvel
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '4c87810b-c6e3-4022-8dd9-81d2f01541a5'; -- Immortal X-Men by Kieron Gillen: dawn-of-krakoa -> the-expansion
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = '4ffb967d-f0d6-44bf-b249-c910857a0bd4'; -- Marvel Masterworks: Captain America Vol. 1: birth-of-marvel -> bronze-age
UPDATE collected_editions SET era_id = 'c4bffdc6-c943-432e-9b61-6b51387076bb' WHERE id = '5236d838-eb06-4a54-bb3d-7ab019a0bf78'; -- X-Force Epic Collection: Armageddon Now: heroes-reborn-return -> current-ongoings
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '565e9fd5-fb03-410c-a583-9289cb96c795'; -- Astonishing X-Men Epic Collection: Gifted: bendis-avengers -> birth-of-marvel
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '56b1e103-fcd5-4b26-bee1-89cc71fa4b9f'; -- The Ultimates By Millar & Hitch Omnibus: marvel-knights-ultimate -> the-expansion
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = '625a9fbe-7509-43f9-bea7-6c13a07e61d0'; -- Incredible Hulk Masterworks Vol. 2: birth-of-marvel -> bronze-age
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '65975c71-3e94-43cb-8b52-773f621c9788'; -- She-Hulk Epic Collection: Breaking the Fourth Wall: event-age -> birth-of-marvel
UPDATE collected_editions SET era_id = 'fe75c870-3888-4405-9c8a-1f0341f19339' WHERE id = '6c70e640-3aa3-44c0-9c0b-75f27c866185'; -- All-New Wolverine By Tom Taylor Omnibus: all-new-all-different -> hickman-saga
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '704614b9-e2e1-40a6-af5a-f88018718f2d'; -- Doctor Strange Epic Collection: A Separate Reality: bronze-age -> birth-of-marvel
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '709098ea-7107-4de3-8448-5108498187af'; -- Daredevil Masterworks Vol. 2: birth-of-marvel -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '717a6e4d-70a5-4374-869d-e8e96915166c'; -- Midnight Sons Omnibus: event-age -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '7571b1e9-3b27-477d-9cb0-793b862f104e'; -- Timeless by Jed MacKay: blood-hunt-doom -> the-expansion
UPDATE collected_editions SET era_id = '93f0e7e8-0cc2-4f06-9090-6ad14520bece' WHERE id = '7f55f21e-0f21-4755-aa42-1affeec97868'; -- Silver Surfer Epic Collection: Resurrection: speculation-crash -> event-age
UPDATE collected_editions SET era_id = 'fe75c870-3888-4405-9c8a-1f0341f19339' WHERE id = '8108efad-07a7-40c6-b2c1-518c6f216fb5'; -- Spider-Verse/Spider-Geddon Omnibus: all-new-all-different -> hickman-saga
UPDATE collected_editions SET era_id = '49fd3e6f-0cd3-48f5-abbe-7c90e59acfa6' WHERE id = '85cdbfbd-3869-490e-9cc5-92d036f7127b'; -- Age of X Complete: hickman-saga -> rise-of-x-men
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '86967fd2-f5c3-47d0-8614-93dabe3ce301'; -- Miles Morales: Spider-Man Omnibus Vol. 1: bendis-avengers -> the-expansion
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '89f526d5-ef38-4bc9-a6c2-b30bb41e614d'; -- Ms. Marvel by G. Willow Wilson Vol. 3: Crushed: hickman-saga -> birth-of-marvel
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '8d291df3-5885-4117-9964-ba178fdfb934'; -- Immortal Iron Fist & The Immortal Weapons Omnibus: bendis-avengers -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '8dff12d6-88c9-490e-839a-36ddf26bdc0c'; -- Avengers Masterworks Vol. 2: birth-of-marvel -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '8f395963-1019-4c61-bbfb-7b82292822db'; -- Ultimatum: bendis-avengers -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '93b5a01f-fcbc-4c26-8a01-c27617a95e29'; -- Ultimate Fantastic Four Omnibus Vol. 1: marvel-knights-ultimate -> the-expansion
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = '946633c7-e16f-4a0b-bb4e-7c47f257ce00'; -- Marvel Masterworks: Iron Man Vol. 1: birth-of-marvel -> bronze-age
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '9acd8991-ffab-43dc-bc9f-0c502972d9b0'; -- Annihilation Epic Collection: Annihilation Day: bendis-avengers -> the-expansion
UPDATE collected_editions SET era_id = '2b73f22c-6333-4928-97ba-78477e5acffe' WHERE id = 'a1881651-eb6f-4417-b718-159989564214'; -- Heroes Reborn (2021): dawn-of-krakoa -> heroes-reborn-return
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'a766be56-4bd1-4c84-be48-a03ce051f8a8'; -- Inhumans Prime / Inhumans vs. X-Men: all-new-all-different -> the-expansion
UPDATE collected_editions SET era_id = 'ef8c9832-e06d-4028-ae89-a2bb5eb13e1c' WHERE id = 'acf91c35-2cce-462d-bf90-33b336907d45'; -- Avengers Epic Collection: Judgment Day: event-age -> dawn-of-krakoa
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = 'adb3a381-063c-47eb-b934-cd498d493564'; -- Captain America Epic Collection: Captain America Lives Again: birth-of-marvel -> bronze-age
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = 'b0bb8995-e895-4c2f-9e77-63705c8e85a1'; -- Astonishing X-Men Epic Collection: Unstoppable: bendis-avengers -> birth-of-marvel
UPDATE collected_editions SET era_id = '93f0e7e8-0cc2-4f06-9090-6ad14520bece' WHERE id = 'b1797def-a13e-4283-bd39-ef52c3d3ee0a'; -- Punisher By Rick Remender Omnibus: hickman-saga -> event-age
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = 'b1e5627c-126b-4f22-abbb-f1e12aefad9b'; -- Ultimate Spider-Man Omnibus Vol. 2 (Bendis): marvel-knights-ultimate -> bronze-age
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'b3d019a1-99e0-4f2e-909a-2716c73984f1'; -- Spider-Man Unlimited Epic Collection: Maximum Clonage: speculation-crash -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'b3d52f6e-3590-45b3-8348-5f018dbc35b1'; -- Miles Morales: Spider-Man Epic Collection: Hero in Training: hickman-saga -> the-expansion
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = 'b5aaa714-0dcb-479a-8417-9727e77d4529'; -- Iron Man Epic Collection: The Golden Avenger: birth-of-marvel -> bronze-age
UPDATE collected_editions SET era_id = '93f0e7e8-0cc2-4f06-9090-6ad14520bece' WHERE id = 'b7564106-0150-4c9b-85c9-dec4636f4992'; -- Fantastic Four Epic Collection: Nobody Gets Out Alive: speculation-crash -> event-age
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = 'b8fedf65-d696-431b-9fad-da558be94d0f'; -- Iron Man Omnibus Vol. 1: birth-of-marvel -> bronze-age
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = 'ba484c2a-a10e-4cc8-af0f-7fd4c11e87a1'; -- Indestructible Hulk: The Complete Collection: hickman-saga -> birth-of-marvel
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = 'bc62ae00-92a4-49a5-b97e-8a7edfb70fc8'; -- Astonishing X-Men by Whedon & Cassaday: Vol. 2 (Unstoppable/Gone): marvel-knights-ultimate -> birth-of-marvel
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = 'bf4f0358-5614-48c1-9ea5-24144950e743'; -- Avengers Forever Omnibus: marvel-knights-ultimate -> birth-of-marvel
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'bfdb2c7c-6db0-4625-acdf-36f609a30e8e'; -- Miles Morales: Ultimate Spider-Man Ultimate Collection: hickman-saga -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'c14147c8-1fcc-4731-aa16-4b2d939e00a7'; -- Avengers West Coast Epic Collection: How the West Was Won: event-age -> the-expansion
UPDATE collected_editions SET era_id = 'ef8c9832-e06d-4028-ae89-a2bb5eb13e1c' WHERE id = '00a03dc6-4bdb-4eb4-9d01-9ab42fbcd95b'; -- Star-Lord by Chip Zdarsky: all-new-all-different -> dawn-of-krakoa
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = 'adb3a381-063c-47eb-b934-cd498d493564'; -- Captain America Epic Collection: Captain America Lives Again: birth-of-marvel -> bronze-age
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'ca323b87-f6c6-45d1-85e3-70e62a01dbe2'; -- Ultimate X-Men Epic Collection: The Tomorrow Children: marvel-knights-ultimate -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'a766be56-4bd1-4c84-be48-a03ce051f8a8'; -- Inhumans Prime / Inhumans vs. X-Men: all-new-all-different -> the-expansion
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '38fe298b-267f-4da8-affe-8f6d751473d3'; -- Warlock by Jim Starlin (Complete Collection): bronze-age -> birth-of-marvel
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'bfdb2c7c-6db0-4625-acdf-36f609a30e8e'; -- Miles Morales: Ultimate Spider-Man Ultimate Collection: hickman-saga -> the-expansion
UPDATE collected_editions SET era_id = '93f0e7e8-0cc2-4f06-9090-6ad14520bece' WHERE id = 'b7564106-0150-4c9b-85c9-dec4636f4992'; -- Fantastic Four Epic Collection: Nobody Gets Out Alive: speculation-crash -> event-age
UPDATE collected_editions SET era_id = '70d862f6-720f-46f0-ac11-b3171abd44c6' WHERE id = '625a9fbe-7509-43f9-bea7-6c13a07e61d0'; -- Incredible Hulk Masterworks Vol. 2: birth-of-marvel -> bronze-age
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'd8c247c5-c45d-4a57-824e-a92d60e2fedc'; -- Ultimate Comics Ultimates by Jonathan Hickman: bendis-avengers -> the-expansion
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '565e9fd5-fb03-410c-a583-9289cb96c795'; -- Astonishing X-Men Epic Collection: Gifted: bendis-avengers -> birth-of-marvel
UPDATE collected_editions SET era_id = 'ef8c9832-e06d-4028-ae89-a2bb5eb13e1c' WHERE id = 'acf91c35-2cce-462d-bf90-33b336907d45'; -- Avengers Epic Collection: Judgment Day: event-age -> dawn-of-krakoa
UPDATE collected_editions SET era_id = '49fd3e6f-0cd3-48f5-abbe-7c90e59acfa6' WHERE id = '85cdbfbd-3869-490e-9cc5-92d036f7127b'; -- Age of X Complete: hickman-saga -> rise-of-x-men
UPDATE collected_editions SET era_id = 'fe75c870-3888-4405-9c8a-1f0341f19339' WHERE id = '6c70e640-3aa3-44c0-9c0b-75f27c866185'; -- All-New Wolverine By Tom Taylor Omnibus: all-new-all-different -> hickman-saga
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '709098ea-7107-4de3-8448-5108498187af'; -- Daredevil Masterworks Vol. 2: birth-of-marvel -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'ee11f188-8ac7-4f39-949e-8fd87c0cacbd'; -- Fall of X Vol. 1: dawn-of-krakoa -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '8dff12d6-88c9-490e-839a-36ddf26bdc0c'; -- Avengers Masterworks Vol. 2: birth-of-marvel -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = 'f142c839-fc74-4125-a9b3-0f9fe51042d2'; -- Ultimate Comics Doomsday Trilogy: bendis-avengers -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '93b5a01f-fcbc-4c26-8a01-c27617a95e29'; -- Ultimate Fantastic Four Omnibus Vol. 1: marvel-knights-ultimate -> the-expansion
UPDATE collected_editions SET era_id = '49fd3e6f-0cd3-48f5-abbe-7c90e59acfa6' WHERE id = '0f5377ee-5991-4b12-a844-d72874a9d18f'; -- Deathlok: The Complete Collection (Original): bronze-age -> rise-of-x-men
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '314b4a75-0d5b-4759-8331-71f129211643'; -- Ultimate Spider-Man Epic Collection: Learning Curve: marvel-knights-ultimate -> the-expansion
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '86967fd2-f5c3-47d0-8614-93dabe3ce301'; -- Miles Morales: Spider-Man Omnibus Vol. 1: bendis-avengers -> the-expansion
UPDATE collected_editions SET era_id = 'eb1a7d39-e8d3-41f1-9ec2-74e2ec3d3be6' WHERE id = '3b1e2200-5d50-4f01-b3b0-6f201666aefb'; -- Sensational She-Hulk by John Byrne Omnibus: event-age -> birth-of-marvel
UPDATE collected_editions SET era_id = 'a9fe2453-0328-4e72-88ac-01d5cbdef337' WHERE id = '10b94252-ba6a-4c14-9a9c-485dc7d7d365'; -- Ultimate Fantastic Four Epic Collection: The Fantastic: marvel-knights-ultimate -> the-expansion

COMMIT;
